"""
Rebuild the Subro Studio dashboard with an explicit headline -> unit hierarchy
and real bar/line chart views (not raw tables), using the confirmed working
viewType='chart' config discovered in try_chart_view.py (chart C3x25g).

Studio's dashboard object is just an ordered list of chart ids (no layout/
sizing/cross-filter wiring - confirmed via DashboardCreateRequest/ChartR in
the SDK's openapi2.py: chartids: list[str] is the entire schema). So
"hierarchy" here means: order charts headline -> unit breakdown -> trend ->
detail table, and title each one so the hierarchy reads top to bottom.
"""
import studio, json

out = open('build_subro_v2.log', 'a')
def w(s): print(s); out.write(s + '\n'); out.flush()

p = studio.proj()  # 0010z

BASE_WHERE = "IsPostedRecovery = true AND Division = 'S'"

def bar_view(x_col, metric_col, metric_label=None):
    return {
        "viewType": "chart",
        "yAxesViewOptions": [{"scale": "linear"}],
        "metricViewOptions": [{
            "name": metric_col, "yAxis": 0, "stacked": False, "sortOrder": 0,
            "percentage": False, "autoGeneratedName": False, "formatAsPercentage": False,
            **({"displayName": metric_label} if metric_label else {}),
        }],
        "dsProps": [], "overMetricNames": False, "tableColumnSortSpec": [],
        "tooltipType": "allPoints", "groupByMetricsOrder": {}, "groupByColorOverrides": {},
        "xColumn": x_col,
    }

def make_chart(title, description, sql, view=None):
    query = {"type": "customSqlRequest", "async": True, "priority": 1, "customsql": sql}
    try:
        kwargs = dict(query=query, title=title, description=description, quiet=True, timeout=180)
        if view is not None:
            kwargs["view"] = view
        c = p.createAndPublishChart(**kwargs)
        cid = c.id if hasattr(c, 'id') else c.get('id')
        w(f"CREATED '{title}' id={cid}")
        return cid
    except Exception as e:
        w(f"ERR '{title}': {str(e)[-800:]}")
        return None

chart_ids = []

# 1. HEADLINE: L30 vs P30 vs Last Complete Month, single row (table by design - a
#    literal single value has no dedicated widget type in Studio; see README note)
sql_headline = f"""
SELECT
  'Last 30 days' AS Window, SUM(GrossRecovery) AS TotalRecovered, COUNT(DISTINCT File_key) AS Files
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE {BASE_WHERE} AND RecoveryDate >= date_sub(current_date(), 30) AND RecoveryDate < current_date()
UNION ALL
SELECT
  'Prior 30 days' AS Window, SUM(GrossRecovery) AS TotalRecovered, COUNT(DISTINCT File_key) AS Files
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE {BASE_WHERE} AND RecoveryDate >= date_sub(current_date(), 60) AND RecoveryDate < date_sub(current_date(), 30)
"""
chart_ids.append(make_chart(
    "01 HEADLINE - Subro $ Recovered, L30 vs P30 (real data)",
    "Headline metric. Compare rows: L30 vs P30 gross $ recovered and file counts. "
    "Source: SubroReports.rpt.RecoveriesbyLOBTableau, IsPostedRecovery=true, Division=S.",
    sql_headline,
))

# 2. UNIT BREAKDOWN (L2 hierarchy): LRU / RCU / SRU, last 30 days, as a bar chart
sql_by_unit = f"""
SELECT
  CASE WHEN Team IN (41,42) THEN 'SRU' WHEN Team = 45 THEN 'RCU' ELSE 'LRU' END AS Unit,
  SUM(GrossRecovery) AS TotalRecovered, COUNT(DISTINCT File_key) AS Files
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE {BASE_WHERE} AND RecoveryDate >= date_sub(current_date(), 30) AND RecoveryDate < current_date()
GROUP BY CASE WHEN Team IN (41,42) THEN 'SRU' WHEN Team = 45 THEN 'RCU' ELSE 'LRU' END
ORDER BY TotalRecovered DESC
"""
chart_ids.append(make_chart(
    "02 UNIT BREAKDOWN - Subro $ Recovered by Unit, L30 (real data)",
    "L2 hierarchy: LRU/RCU/SRU derived from rep team (41/42=SRU, 45=RCU, else=LRU). "
    "Same source as headline, last 30 days.",
    sql_by_unit,
    view=bar_view("Unit", "TotalRecovered", "$ Recovered"),
))

# 3. TREND: daily, last 90 days, as a bar/line chart (this is the one already proven
#    to save as viewType=chart in try_chart_view.py)
sql_daily = f"""
SELECT CAST(RecoveryDate AS date) AS RecoveryDate, SUM(GrossRecovery) AS GrossRecovery
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE {BASE_WHERE} AND RecoveryDate >= date_sub(current_date(), 90)
GROUP BY CAST(RecoveryDate AS date)
ORDER BY RecoveryDate
"""
chart_ids.append(make_chart(
    "03 TREND - Subro $ Recovered Daily, 90d (real data)",
    "Daily posted $ recovered, last 90 days, real data. Click a bar in Studio to inspect that day's rows.",
    sql_daily,
    view=bar_view("RecoveryDate", "GrossRecovery", "$ Recovered"),
))

# 4. TREND by unit: same 90-day window split by unit so unit trend is visible, not just total
sql_daily_unit = f"""
SELECT CAST(RecoveryDate AS date) AS RecoveryDate,
  CASE WHEN Team IN (41,42) THEN 'SRU' WHEN Team = 45 THEN 'RCU' ELSE 'LRU' END AS Unit,
  SUM(GrossRecovery) AS GrossRecovery
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE {BASE_WHERE} AND RecoveryDate >= date_sub(current_date(), 90)
GROUP BY CAST(RecoveryDate AS date), CASE WHEN Team IN (41,42) THEN 'SRU' WHEN Team = 45 THEN 'RCU' ELSE 'LRU' END
ORDER BY RecoveryDate
"""
chart_ids.append(make_chart(
    "04 TREND BY UNIT - Subro $ Recovered Daily, 90d, LRU-RCU-SRU (real data)",
    "Same 90-day window as chart 03, split by unit for the L2 drill-down view.",
    sql_daily_unit,
    view=bar_view("RecoveryDate", "GrossRecovery", "$ Recovered"),
))

# 5. L3 DETAIL: top files by $ recovered, last 60 days (kept as a table - this is
#    detail-grain data, a table is the right widget for it)
sql_top_files = f"""
SELECT File_key, ContractualClientCode AS Client, Parent_Name AS Parent, Team,
  CASE WHEN Team IN (41,42) THEN 'SRU' WHEN Team = 45 THEN 'RCU' ELSE 'LRU' END AS Unit,
  SUM(GrossRecovery) AS Recovered60d, MAX(RecoveryDate) AS LastRecoveryDate
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE {BASE_WHERE} AND RecoveryDate >= date_sub(current_date(), 60)
GROUP BY File_key, ContractualClientCode, Parent_Name, Team
ORDER BY Recovered60d DESC
LIMIT 25
"""
chart_ids.append(make_chart(
    "05 DETAIL - Top 25 Files by $ Recovered, L60 (real data)",
    "L3 drill-down detail. One row per file with a posting in the last 60 days, ranked by $ recovered.",
    sql_top_files,
))

chart_ids = [c for c in chart_ids if c]
w(f"chart_ids (ordered headline->unit->trend->trend_by_unit->detail): {chart_ids}")

if chart_ids:
    try:
        d = p.getDashboard("RPS $ Recovered - Executive View (real data)", quiet=True)
        res = d.updateDashboard(
            chart_ids=chart_ids,
            description="RPS Subrogation $ Recovered - executive hierarchy: headline (L30 vs P30) -> "
                         "unit breakdown (LRU/RCU/SRU) -> 90-day trend (total and by unit) -> top-file "
                         "detail. Real data only, SubroReports.rpt.RecoveriesbyLOBTableau. "
                         "Rebuilt 2026-09-15 per feedback that the dashboard needed pillar/unit hierarchy.",
            quiet=True, timeout=180,
        )
        w(f"UPDATED existing dashboard D07my1: {str(res)[:500]}")
    except Exception as e:
        w(f"ERR updating dashboard, falling back to create new: {str(e)[-800:]}")
        try:
            d = p.createDashboard(
                name="RPS $ Recovered - Executive View v2 (real data)",
                description="Hierarchical rebuild: headline, unit breakdown, trend, detail.",
                chartids=chart_ids, quiet=True, timeout=180,
            )
            w(f"CREATED new dashboard: {str(d)[:500]}")
        except Exception as e2:
            w(f"ERR creating fallback dashboard: {str(e2)[-800:]}")

w("DONE")
out.close()
