import studio, json, time

out = open('build_studio_dashboard.txt', 'a')
def w(s): out.write(s+'\n'); out.flush()

p = studio.proj()  # project 0010z (Subro) - real, confirmed dated $ recovered source

sql_daily = """
SELECT CAST(RecoveryDate AS date) AS RecoveryDate, SUM(GrossRecovery) AS GrossRecovery
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE IsPostedRecovery = true AND Division = 'S'
  AND RecoveryDate >= date_sub(current_date(), 90)
GROUP BY CAST(RecoveryDate AS date)
ORDER BY RecoveryDate
"""

sql_by_team = """
SELECT Team, SUM(GrossRecovery) AS GrossRecovery, COUNT(DISTINCT File_key) AS Files
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE IsPostedRecovery = true AND Division = 'S'
  AND RecoveryDate >= date_sub(current_date(), 30)
GROUP BY Team
ORDER BY GrossRecovery DESC
"""

sql_by_lob = """
SELECT LOB, SUM(GrossRecovery) AS GrossRecovery
FROM `SubroReports.rpt.RecoveriesbyLOBTableau`
WHERE IsPostedRecovery = true AND Division = 'S'
  AND RecoveryDate >= date_sub(current_date(), 30)
GROUP BY LOB
ORDER BY GrossRecovery DESC
"""

def make_chart(title, description, sql):
    query = {"type": "customSqlRequest", "async": True, "priority": 1, "customsql": sql}
    try:
        c = p.createAndPublishChart(query=query, title=title, description=description, quiet=True, timeout=120)
        w(f"CREATED chart '{title}' id={c.id if hasattr(c,'id') else c.get('id')}")
        return c
    except Exception as e:
        w(f"ERR creating chart '{title}': {str(e)[-600:]}")
        return None

c1 = make_chart("RPS Exec Dashboard - Subro $ Recovered Daily (90d, real data)",
                 "Real daily $ recovered from SubroReports.rpt.RecoveriesbyLOBTableau, last 90 days.",
                 sql_daily)
c2 = make_chart("RPS Exec Dashboard - Subro $ Recovered by Team (L30, real data)",
                 "Real $ recovered by rep team, last 30 days, from SubroReports.rpt.RecoveriesbyLOBTableau.",
                 sql_by_team)
c3 = make_chart("RPS Exec Dashboard - Subro $ Recovered by LOB (L30, real data)",
                 "Real $ recovered by line of business, last 30 days, from SubroReports.rpt.RecoveriesbyLOBTableau.",
                 sql_by_lob)

chart_ids = [c.id if hasattr(c,'id') else c.get('id') for c in [c1,c2,c3] if c is not None]
w(f"chart_ids: {chart_ids}")

if chart_ids:
    try:
        d = p.createDashboard(name="RPS $ Recovered - Executive View (real data)",
                               description="Real $ recovered dashboard for Subrogation, built from SubroReports.rpt.RecoveriesbyLOBTableau. "
                                           "Generated by Sidd Sampath's exec dashboard project.",
                               chartids=chart_ids, quiet=True, timeout=120)
        w(f"CREATED dashboard name={d.name if hasattr(d,'name') else d.get('name')} full={str(d)[:1000]}")
    except Exception as e:
        w(f"ERR creating dashboard: {str(e)[-800:]}")

w("DONE")
out.close()
