"""
Build a companion Studio dashboard for the COB pillar in project 0012k.
This has to be a separate dashboard object from the Subro one (D07my1, in
project 0010z) because Studio charts/dashboards are project-scoped and the
COB data source (CarlQryRun on TRGACAP3) is only registered in 0012k -
confirmed there is no cross-project dashboard object in this SDK.

Honesty constraint carried over from the real-data research: the only COB
number reachable here is all-time INVOICED $ (no date column exists on
overlap_detection.InvestigationInvoices), so this is explicitly not a
last-30-days recovered figure. Every chart title says so.
"""
import studio_cob as studio, json

out = open('build_cob_v1.log', 'a')
def w(s): print(s); out.write(s + '\n'); out.flush()

p = studio.proj()  # 0012k

def bar_view(x_col, metric_col, metric_label=None):
    return {
        "viewType": "chart",
        "yAxesViewOptions": [{"scale": "linear"}],
        "metricViewOptions": [{
            "name": metric_col, "yAxis": 0, "stacked": False, "sortOrder": 0,
            "percentage": False, "autoGeneratedName": False, "formatAsPercentage": False,
            **({"displayName": metric_label} if metric_label else {}),
        }],
        "dsProps": [], "overMetricNames": False, "tableColumnSortSpec": [],
        "tooltipType": "allPoints", "groupByMetricsOrder": {}, "groupByColorOverrides": {},
        "xColumn": x_col,
    }

def make_chart(title, description, sql, view=None):
    query = {"type": "customSqlRequest", "async": True, "priority": 1, "customsql": sql}
    try:
        kwargs = dict(query=query, title=title, description=description, quiet=True, timeout=180)
        if view is not None:
            kwargs["view"] = view
        c = p.createAndPublishChart(**kwargs)
        cid = c.id if hasattr(c, 'id') else c.get('id')
        w(f"CREATED '{title}' id={cid}")
        return cid
    except Exception as e:
        w(f"ERR '{title}': {str(e)[-800:]}")
        return None

chart_ids = []

# 1. HEADLINE: all-time invoiced $ and investigation counts (table - single summary row)
sql_headline = """
SELECT
  COUNT(DISTINCT i.InvestigationID) AS Investigations,
  SUM(CASE WHEN i.InvoiceRecorded > 0 THEN 1 ELSE 0 END) AS InvestigationsWithPositiveInvoice,
  SUM(i.InvoiceRecorded) AS TotalInvoicedAllTime
FROM `CarlQryRun.overlap_detection.InvestigationInvoices` i
"""
chart_ids.append(make_chart(
    "01 HEADLINE - COB $ Invoiced, All-Time (real data, no date field exists)",
    "Headline metric for COB. This is ALL-TIME invoiced $, not a last-30-days figure - "
    "overlap_detection.InvestigationInvoices has no date column. See the RPS design doc "
    "Part 2 (COB source section) for the open question on where the dated posted-recovery "
    "table lives. Source: CarlQryRun.overlap_detection.InvestigationInvoices, project 0012k.",
    sql_headline,
))

# 2. L2 BREAKDOWN by client (program line not resolvable without SmartII audit-type
# access from this session, so client code is the best real L2 available today)
sql_by_client = """
SELECT c.ClientCode, COUNT(DISTINCT i.InvestigationID) n_investigations,
       SUM(i.InvoiceRecorded) total_invoiced
FROM `CarlQryRun.overlap_detection.InvestigationInvoices` i
JOIN (
    SELECT InvestigationID, MAX(ClientCode) AS ClientCode
    FROM `CarlQryRun.overlap_detection.CEMOverlapsAndSmartIIResults`
    WHERE InvestigationID IS NOT NULL
    GROUP BY InvestigationID
) c ON c.InvestigationID = i.InvestigationID
GROUP BY c.ClientCode
ORDER BY total_invoiced DESC
LIMIT 20
"""
chart_ids.append(make_chart(
    "02 BY CLIENT - COB $ Invoiced, Top 20 Clients, All-Time (real data)",
    "L2 view. Program-line breakdown (the design doc's recommended default) is not "
    "resolvable from this session's Studio access - it requires SmartII tblAudit/"
    "investigation-type, which is not a registered source here. Client code is the best "
    "real cut available today.",
    sql_by_client,
    view=bar_view("ClientCode", "total_invoiced", "$ Invoiced (all-time)"),
))

# 3. Disposition breakdown - the closest thing to a status/program taxonomy actually
# reachable here (InvestigationStatus on CEMOverlapsAndSmartIIResults)
sql_by_status = """
SELECT InvestigationStatus, COUNT(*) AS n
FROM `CarlQryRun.overlap_detection.CEMOverlapsAndSmartIIResults`
WHERE InvestigationStatus IS NOT NULL
GROUP BY InvestigationStatus
ORDER BY n DESC
LIMIT 20
"""
chart_ids.append(make_chart(
    "03 DISPOSITION - COB Investigation Status Counts, All-Time (real data)",
    "Investigation disposition taxonomy (Overpayment, Clsd CP No Overpay, Clsd PrePay "
    "Savings, etc.) from CEMOverlapsAndSmartIIResults.InvestigationStatus - the closest "
    "real substitute for a program-line L2 split available in this project.",
    sql_by_status,
    view=bar_view("InvestigationStatus", "n", "Investigations"),
))

# 4. L3 DETAIL: top investigations by invoiced $
sql_top_inv = """
SELECT i.InvestigationID, c.ClientCode, i.InvoiceRecorded
FROM `CarlQryRun.overlap_detection.InvestigationInvoices` i
JOIN (
    SELECT InvestigationID, MAX(ClientCode) AS ClientCode
    FROM `CarlQryRun.overlap_detection.CEMOverlapsAndSmartIIResults`
    WHERE InvestigationID IS NOT NULL
    GROUP BY InvestigationID
) c ON c.InvestigationID = i.InvestigationID
ORDER BY i.InvoiceRecorded DESC
LIMIT 25
"""
chart_ids.append(make_chart(
    "04 DETAIL - Top 25 Investigations by $ Invoiced, All-Time (real data)",
    "L3 drill-down detail, one row per investigation.",
    sql_top_inv,
))

chart_ids = [c for c in chart_ids if c]
w(f"chart_ids (headline->by_client->disposition->detail): {chart_ids}")

if chart_ids:
    try:
        exists = p.dashboardExists("RPS COB $ Invoiced - Executive View (real data)", quiet=True)
    except Exception as e:
        w(f"dashboardExists check failed, assuming not present: {str(e)[-300:]}")
        exists = False
    try:
        if exists:
            d = p.getDashboard("RPS COB $ Invoiced - Executive View (real data)", quiet=True)
            res = d.updateDashboard(chart_ids=chart_ids, quiet=True, timeout=180)
            w(f"UPDATED existing COB dashboard: {str(res)[:500]}")
        else:
            d = p.createDashboard(
                name="RPS COB $ Invoiced - Executive View (real data)",
                description="RPS COB pillar - headline (all-time invoiced $) -> by-client breakdown -> "
                             "investigation-status disposition -> top-investigation detail. Real data "
                             "only, CarlQryRun.overlap_detection tables, project 0012k. This pillar has "
                             "no dated posted-recovery source reachable from this session; see the "
                             "RPS_Recovered_Exec_Dashboard_Design.md Part 2 open questions.",
                chartids=chart_ids, quiet=True, timeout=180,
            )
            w(f"CREATED COB dashboard: {str(d)[:500]}")
    except Exception as e:
        w(f"ERR creating/updating COB dashboard: {str(e)[-800:]}")

w("DONE")
out.close()
