import studio, json, time

out = open('try_chart_view.txt', 'a')
def w(s): out.write(s+'\n'); out.flush()

p = studio.proj()

# Try updating an existing chart's view to a bar/line chart type, referencing real columns
view_cfg = {
    "viewType": "chart",
    "yAxesViewOptions": [{"scale": "linear"}],
    "metricViewOptions": [{"name": "GrossRecovery", "yAxis": 0, "stacked": False, "sortOrder": 0,
                            "percentage": False, "autoGeneratedName": False, "formatAsPercentage": False}],
    "dsProps": [], "overMetricNames": False, "tableColumnSortSpec": [],
    "tooltipType": "allPoints", "groupByMetricsOrder": {}, "groupByColorOverrides": {},
    "xColumn": "RecoveryDate",
}

query = {"type": "customSqlRequest", "async": True, "priority": 1, "customsql":
    "SELECT CAST(RecoveryDate AS date) AS RecoveryDate, SUM(GrossRecovery) AS GrossRecovery "
    "FROM `SubroReports.rpt.RecoveriesbyLOBTableau` WHERE IsPostedRecovery = true AND Division = 'S' "
    "AND RecoveryDate >= date_sub(current_date(), 90) GROUP BY CAST(RecoveryDate AS date) ORDER BY RecoveryDate"}

try:
    c = p.createChart(title="TEST viewType chart attempt", description="testing bar/line view config",
                       query=query, view=view_cfg, quiet=True, timeout=120)
    w(f"created id={c.id if hasattr(c,'id') else c.get('id')}")
    # fetch it back to see what stuck
    got = p.getChart(c.id if hasattr(c,'id') else c.get('id'), quiet=True)
    w("VIEW AFTER SAVE: " + json.dumps(got.get('view'), default=str))
except Exception as e:
    w(f"ERR: {str(e)[-800:]}")

w("DONE")
out.close()
